/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as UploadSongRouteImport } from './routes/upload-song'
import { Route as UploadSingleRouteImport } from './routes/upload-single'
import { Route as UploadAlbumRouteImport } from './routes/upload-album'
import { Route as Top_musicRouteImport } from './routes/top_music'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SpotlightRouteImport } from './routes/spotlight'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Recently_playedRouteImport } from './routes/recently_played'
import { Route as PurchasedRouteImport } from './routes/purchased'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PointSystemRouteImport } from './routes/point-system'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as New_musicRouteImport } from './routes/new_music'
import { Route as My_playlistsRouteImport } from './routes/my_playlists'
import { Route as MySongsRouteImport } from './routes/my-songs'
import { Route as MyAppsRouteImport } from './routes/my-apps'
import { Route as MyAlbumsRouteImport } from './routes/my-albums'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterestRouteImport } from './routes/interest'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GoProRouteImport } from './routes/go-pro'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FameRouteImport } from './routes/fame'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as BecomeRouteImport } from './routes/become'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TracksSlugRouteImport } from './routes/tracks.$slug'
import { Route as PlaylistsSlugRouteImport } from './routes/playlists.$slug'
import { Route as PaymentCinetpayCallbackRouteImport } from './routes/payment.cinetpay-callback'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as ArtistWithdrawRouteImport } from './routes/artist.withdraw'
import { Route as ArtistUpgradeRouteImport } from './routes/artist.upgrade'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AlbumsSlugRouteImport } from './routes/albums.$slug'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTracksRouteImport } from './routes/admin.tracks'
import { Route as AdminTopupsRouteImport } from './routes/admin.topups'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminCopyrightsRouteImport } from './routes/admin.copyrights'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminCinetpayRouteImport } from './routes/admin.cinetpay'
import { Route as AdminBrandingRouteImport } from './routes/admin.branding'
import { Route as AdminBannedIpsRouteImport } from './routes/admin.banned-ips'
import { Route as AdminBankReceiptsRouteImport } from './routes/admin.bank-receipts'
import { Route as AdminArtistsRouteImport } from './routes/admin.artists'
import { Route as AdminArtistVerificationRouteImport } from './routes/admin.artist-verification'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as ApiPublicSeedTestAccountsRouteImport } from './routes/api/public/seed-test-accounts'
import { Route as ApiPublicFlutterwaveWebhookRouteImport } from './routes/api/public/flutterwave-webhook'
import { Route as ApiPublicCinetpayWebhookRouteImport } from './routes/api/public/cinetpay-webhook'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadSongRoute = UploadSongRouteImport.update({
  id: '/upload-song',
  path: '/upload-song',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadSingleRoute = UploadSingleRouteImport.update({
  id: '/upload-single',
  path: '/upload-single',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadAlbumRoute = UploadAlbumRouteImport.update({
  id: '/upload-album',
  path: '/upload-album',
  getParentRoute: () => rootRouteImport,
} as any)
const Top_musicRoute = Top_musicRouteImport.update({
  id: '/top_music',
  path: '/top_music',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotlightRoute = SpotlightRouteImport.update({
  id: '/spotlight',
  path: '/spotlight',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Recently_playedRoute = Recently_playedRouteImport.update({
  id: '/recently_played',
  path: '/recently_played',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasedRoute = PurchasedRouteImport.update({
  id: '/purchased',
  path: '/purchased',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PointSystemRoute = PointSystemRouteImport.update({
  id: '/point-system',
  path: '/point-system',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const New_musicRoute = New_musicRouteImport.update({
  id: '/new_music',
  path: '/new_music',
  getParentRoute: () => rootRouteImport,
} as any)
const My_playlistsRoute = My_playlistsRouteImport.update({
  id: '/my_playlists',
  path: '/my_playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const MySongsRoute = MySongsRouteImport.update({
  id: '/my-songs',
  path: '/my-songs',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAppsRoute = MyAppsRouteImport.update({
  id: '/my-apps',
  path: '/my-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAlbumsRoute = MyAlbumsRouteImport.update({
  id: '/my-albums',
  path: '/my-albums',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestRoute = InterestRouteImport.update({
  id: '/interest',
  path: '/interest',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GoProRoute = GoProRouteImport.update({
  id: '/go-pro',
  path: '/go-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FameRoute = FameRouteImport.update({
  id: '/fame',
  path: '/fame',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeRoute = BecomeRouteImport.update({
  id: '/become',
  path: '/become',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TracksSlugRoute = TracksSlugRouteImport.update({
  id: '/tracks/$slug',
  path: '/tracks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsSlugRoute = PlaylistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlaylistsRoute,
} as any)
const PaymentCinetpayCallbackRoute = PaymentCinetpayCallbackRouteImport.update({
  id: '/payment/cinetpay-callback',
  path: '/payment/cinetpay-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistWithdrawRoute = ArtistWithdrawRouteImport.update({
  id: '/artist/withdraw',
  path: '/artist/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistUpgradeRoute = ArtistUpgradeRouteImport.update({
  id: '/artist/upgrade',
  path: '/artist/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsSlugRoute = AlbumsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AlbumsRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTracksRoute = AdminTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTopupsRoute = AdminTopupsRouteImport.update({
  id: '/topups',
  path: '/topups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCopyrightsRoute = AdminCopyrightsRouteImport.update({
  id: '/copyrights',
  path: '/copyrights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCinetpayRoute = AdminCinetpayRouteImport.update({
  id: '/cinetpay',
  path: '/cinetpay',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandingRoute = AdminBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannedIpsRoute = AdminBannedIpsRouteImport.update({
  id: '/banned-ips',
  path: '/banned-ips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBankReceiptsRoute = AdminBankReceiptsRouteImport.update({
  id: '/bank-receipts',
  path: '/bank-receipts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistsRoute = AdminArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistVerificationRoute = AdminArtistVerificationRouteImport.update({
  id: '/artist-verification',
  path: '/artist-verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSeedTestAccountsRoute =
  ApiPublicSeedTestAccountsRouteImport.update({
    id: '/api/public/seed-test-accounts',
    path: '/api/public/seed-test-accounts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFlutterwaveWebhookRoute =
  ApiPublicFlutterwaveWebhookRouteImport.update({
    id: '/api/public/flutterwave-webhook',
    path: '/api/public/flutterwave-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCinetpayWebhookRoute =
  ApiPublicCinetpayWebhookRouteImport.update({
    id: '/api/public/cinetpay-webhook',
    path: '/api/public/cinetpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/albums': typeof AlbumsRouteWithChildren
  '/become': typeof BecomeRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/fame': typeof FameRoute
  '/faq': typeof FaqRoute
  '/favourites': typeof FavouritesRoute
  '/feed': typeof FeedRoute
  '/following': typeof FollowingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/genres': typeof GenresRoute
  '/go-pro': typeof GoProRoute
  '/import': typeof ImportRoute
  '/interest': typeof InterestRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-albums': typeof MyAlbumsRoute
  '/my-apps': typeof MyAppsRoute
  '/my-songs': typeof MySongsRoute
  '/my_playlists': typeof My_playlistsRoute
  '/new_music': typeof New_musicRoute
  '/notifications': typeof NotificationsRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/point-system': typeof PointSystemRoute
  '/profile': typeof ProfileRoute
  '/purchased': typeof PurchasedRoute
  '/recently_played': typeof Recently_playedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/spotlight': typeof SpotlightRoute
  '/subscription': typeof SubscriptionRoute
  '/top_music': typeof Top_musicRoute
  '/upload-album': typeof UploadAlbumRoute
  '/upload-single': typeof UploadSingleRoute
  '/upload-song': typeof UploadSongRoute
  '/wallet': typeof WalletRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/artist-verification': typeof AdminArtistVerificationRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/bank-receipts': typeof AdminBankReceiptsRoute
  '/admin/banned-ips': typeof AdminBannedIpsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/cinetpay': typeof AdminCinetpayRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/copyrights': typeof AdminCopyrightsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/artist/upgrade': typeof ArtistUpgradeRoute
  '/artist/withdraw': typeof ArtistWithdrawRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/cinetpay-callback': typeof PaymentCinetpayCallbackRoute
  '/playlists/$slug': typeof PlaylistsSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/cinetpay-webhook': typeof ApiPublicCinetpayWebhookRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/seed-test-accounts': typeof ApiPublicSeedTestAccountsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/become': typeof BecomeRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/fame': typeof FameRoute
  '/faq': typeof FaqRoute
  '/favourites': typeof FavouritesRoute
  '/feed': typeof FeedRoute
  '/following': typeof FollowingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/genres': typeof GenresRoute
  '/go-pro': typeof GoProRoute
  '/import': typeof ImportRoute
  '/interest': typeof InterestRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-albums': typeof MyAlbumsRoute
  '/my-apps': typeof MyAppsRoute
  '/my-songs': typeof MySongsRoute
  '/my_playlists': typeof My_playlistsRoute
  '/new_music': typeof New_musicRoute
  '/notifications': typeof NotificationsRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/point-system': typeof PointSystemRoute
  '/profile': typeof ProfileRoute
  '/purchased': typeof PurchasedRoute
  '/recently_played': typeof Recently_playedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/spotlight': typeof SpotlightRoute
  '/subscription': typeof SubscriptionRoute
  '/top_music': typeof Top_musicRoute
  '/upload-album': typeof UploadAlbumRoute
  '/upload-single': typeof UploadSingleRoute
  '/upload-song': typeof UploadSongRoute
  '/wallet': typeof WalletRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/artist-verification': typeof AdminArtistVerificationRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/bank-receipts': typeof AdminBankReceiptsRoute
  '/admin/banned-ips': typeof AdminBannedIpsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/cinetpay': typeof AdminCinetpayRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/copyrights': typeof AdminCopyrightsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/artist/upgrade': typeof ArtistUpgradeRoute
  '/artist/withdraw': typeof ArtistWithdrawRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/cinetpay-callback': typeof PaymentCinetpayCallbackRoute
  '/playlists/$slug': typeof PlaylistsSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/cinetpay-webhook': typeof ApiPublicCinetpayWebhookRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/seed-test-accounts': typeof ApiPublicSeedTestAccountsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/albums': typeof AlbumsRouteWithChildren
  '/become': typeof BecomeRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/fame': typeof FameRoute
  '/faq': typeof FaqRoute
  '/favourites': typeof FavouritesRoute
  '/feed': typeof FeedRoute
  '/following': typeof FollowingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/genres': typeof GenresRoute
  '/go-pro': typeof GoProRoute
  '/import': typeof ImportRoute
  '/interest': typeof InterestRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-albums': typeof MyAlbumsRoute
  '/my-apps': typeof MyAppsRoute
  '/my-songs': typeof MySongsRoute
  '/my_playlists': typeof My_playlistsRoute
  '/new_music': typeof New_musicRoute
  '/notifications': typeof NotificationsRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/point-system': typeof PointSystemRoute
  '/profile': typeof ProfileRoute
  '/purchased': typeof PurchasedRoute
  '/recently_played': typeof Recently_playedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/spotlight': typeof SpotlightRoute
  '/subscription': typeof SubscriptionRoute
  '/top_music': typeof Top_musicRoute
  '/upload-album': typeof UploadAlbumRoute
  '/upload-single': typeof UploadSingleRoute
  '/upload-song': typeof UploadSongRoute
  '/wallet': typeof WalletRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/artist-verification': typeof AdminArtistVerificationRoute
  '/admin/artists': typeof AdminArtistsRoute
  '/admin/bank-receipts': typeof AdminBankReceiptsRoute
  '/admin/banned-ips': typeof AdminBannedIpsRoute
  '/admin/branding': typeof AdminBrandingRoute
  '/admin/cinetpay': typeof AdminCinetpayRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/copyrights': typeof AdminCopyrightsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/artist/upgrade': typeof ArtistUpgradeRoute
  '/artist/withdraw': typeof ArtistWithdrawRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/payment/cinetpay-callback': typeof PaymentCinetpayCallbackRoute
  '/playlists/$slug': typeof PlaylistsSlugRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/cinetpay-webhook': typeof ApiPublicCinetpayWebhookRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
  '/api/public/seed-test-accounts': typeof ApiPublicSeedTestAccountsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/albums'
    | '/become'
    | '/blogs'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/discover'
    | '/fame'
    | '/faq'
    | '/favourites'
    | '/feed'
    | '/following'
    | '/forgot-password'
    | '/genres'
    | '/go-pro'
    | '/import'
    | '/interest'
    | '/login'
    | '/messages'
    | '/my-albums'
    | '/my-apps'
    | '/my-songs'
    | '/my_playlists'
    | '/new_music'
    | '/notifications'
    | '/playlists'
    | '/point-system'
    | '/profile'
    | '/purchased'
    | '/recently_played'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/signup'
    | '/spotlight'
    | '/subscription'
    | '/top_music'
    | '/upload-album'
    | '/upload-single'
    | '/upload-song'
    | '/wallet'
    | '/admin/announcements'
    | '/admin/artist-verification'
    | '/admin/artists'
    | '/admin/bank-receipts'
    | '/admin/banned-ips'
    | '/admin/branding'
    | '/admin/cinetpay'
    | '/admin/comments'
    | '/admin/copyrights'
    | '/admin/faq'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/topups'
    | '/admin/tracks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/albums/$slug'
    | '/articles/$slug'
    | '/artist/upgrade'
    | '/artist/withdraw'
    | '/artists/$slug'
    | '/pages/$slug'
    | '/payment/callback'
    | '/payment/cinetpay-callback'
    | '/playlists/$slug'
    | '/tracks/$slug'
    | '/admin/'
    | '/api/public/cinetpay-webhook'
    | '/api/public/flutterwave-webhook'
    | '/api/public/seed-test-accounts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/become'
    | '/blogs'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/discover'
    | '/fame'
    | '/faq'
    | '/favourites'
    | '/feed'
    | '/following'
    | '/forgot-password'
    | '/genres'
    | '/go-pro'
    | '/import'
    | '/interest'
    | '/login'
    | '/messages'
    | '/my-albums'
    | '/my-apps'
    | '/my-songs'
    | '/my_playlists'
    | '/new_music'
    | '/notifications'
    | '/playlists'
    | '/point-system'
    | '/profile'
    | '/purchased'
    | '/recently_played'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/signup'
    | '/spotlight'
    | '/subscription'
    | '/top_music'
    | '/upload-album'
    | '/upload-single'
    | '/upload-song'
    | '/wallet'
    | '/admin/announcements'
    | '/admin/artist-verification'
    | '/admin/artists'
    | '/admin/bank-receipts'
    | '/admin/banned-ips'
    | '/admin/branding'
    | '/admin/cinetpay'
    | '/admin/comments'
    | '/admin/copyrights'
    | '/admin/faq'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/topups'
    | '/admin/tracks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/albums/$slug'
    | '/articles/$slug'
    | '/artist/upgrade'
    | '/artist/withdraw'
    | '/artists/$slug'
    | '/pages/$slug'
    | '/payment/callback'
    | '/payment/cinetpay-callback'
    | '/playlists/$slug'
    | '/tracks/$slug'
    | '/admin'
    | '/api/public/cinetpay-webhook'
    | '/api/public/flutterwave-webhook'
    | '/api/public/seed-test-accounts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/albums'
    | '/become'
    | '/blogs'
    | '/contact'
    | '/dashboard'
    | '/developers'
    | '/discover'
    | '/fame'
    | '/faq'
    | '/favourites'
    | '/feed'
    | '/following'
    | '/forgot-password'
    | '/genres'
    | '/go-pro'
    | '/import'
    | '/interest'
    | '/login'
    | '/messages'
    | '/my-albums'
    | '/my-apps'
    | '/my-songs'
    | '/my_playlists'
    | '/new_music'
    | '/notifications'
    | '/playlists'
    | '/point-system'
    | '/profile'
    | '/purchased'
    | '/recently_played'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/signup'
    | '/spotlight'
    | '/subscription'
    | '/top_music'
    | '/upload-album'
    | '/upload-single'
    | '/upload-song'
    | '/wallet'
    | '/admin/announcements'
    | '/admin/artist-verification'
    | '/admin/artists'
    | '/admin/bank-receipts'
    | '/admin/banned-ips'
    | '/admin/branding'
    | '/admin/cinetpay'
    | '/admin/comments'
    | '/admin/copyrights'
    | '/admin/faq'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/topups'
    | '/admin/tracks'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/albums/$slug'
    | '/articles/$slug'
    | '/artist/upgrade'
    | '/artist/withdraw'
    | '/artists/$slug'
    | '/pages/$slug'
    | '/payment/callback'
    | '/payment/cinetpay-callback'
    | '/playlists/$slug'
    | '/tracks/$slug'
    | '/admin/'
    | '/api/public/cinetpay-webhook'
    | '/api/public/flutterwave-webhook'
    | '/api/public/seed-test-accounts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlbumsRoute: typeof AlbumsRouteWithChildren
  BecomeRoute: typeof BecomeRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  DiscoverRoute: typeof DiscoverRoute
  FameRoute: typeof FameRoute
  FaqRoute: typeof FaqRoute
  FavouritesRoute: typeof FavouritesRoute
  FeedRoute: typeof FeedRoute
  FollowingRoute: typeof FollowingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GenresRoute: typeof GenresRoute
  GoProRoute: typeof GoProRoute
  ImportRoute: typeof ImportRoute
  InterestRoute: typeof InterestRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MyAlbumsRoute: typeof MyAlbumsRoute
  MyAppsRoute: typeof MyAppsRoute
  MySongsRoute: typeof MySongsRoute
  My_playlistsRoute: typeof My_playlistsRoute
  New_musicRoute: typeof New_musicRoute
  NotificationsRoute: typeof NotificationsRoute
  PlaylistsRoute: typeof PlaylistsRouteWithChildren
  PointSystemRoute: typeof PointSystemRoute
  ProfileRoute: typeof ProfileRoute
  PurchasedRoute: typeof PurchasedRoute
  Recently_playedRoute: typeof Recently_playedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SpotlightRoute: typeof SpotlightRoute
  SubscriptionRoute: typeof SubscriptionRoute
  Top_musicRoute: typeof Top_musicRoute
  UploadAlbumRoute: typeof UploadAlbumRoute
  UploadSingleRoute: typeof UploadSingleRoute
  UploadSongRoute: typeof UploadSongRoute
  WalletRoute: typeof WalletRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArtistUpgradeRoute: typeof ArtistUpgradeRoute
  ArtistWithdrawRoute: typeof ArtistWithdrawRoute
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  PaymentCinetpayCallbackRoute: typeof PaymentCinetpayCallbackRoute
  TracksSlugRoute: typeof TracksSlugRoute
  ApiPublicCinetpayWebhookRoute: typeof ApiPublicCinetpayWebhookRoute
  ApiPublicFlutterwaveWebhookRoute: typeof ApiPublicFlutterwaveWebhookRoute
  ApiPublicSeedTestAccountsRoute: typeof ApiPublicSeedTestAccountsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-song': {
      id: '/upload-song'
      path: '/upload-song'
      fullPath: '/upload-song'
      preLoaderRoute: typeof UploadSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-single': {
      id: '/upload-single'
      path: '/upload-single'
      fullPath: '/upload-single'
      preLoaderRoute: typeof UploadSingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-album': {
      id: '/upload-album'
      path: '/upload-album'
      fullPath: '/upload-album'
      preLoaderRoute: typeof UploadAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top_music': {
      id: '/top_music'
      path: '/top_music'
      fullPath: '/top_music'
      preLoaderRoute: typeof Top_musicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotlight': {
      id: '/spotlight'
      path: '/spotlight'
      fullPath: '/spotlight'
      preLoaderRoute: typeof SpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recently_played': {
      id: '/recently_played'
      path: '/recently_played'
      fullPath: '/recently_played'
      preLoaderRoute: typeof Recently_playedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchased': {
      id: '/purchased'
      path: '/purchased'
      fullPath: '/purchased'
      preLoaderRoute: typeof PurchasedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/point-system': {
      id: '/point-system'
      path: '/point-system'
      fullPath: '/point-system'
      preLoaderRoute: typeof PointSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new_music': {
      id: '/new_music'
      path: '/new_music'
      fullPath: '/new_music'
      preLoaderRoute: typeof New_musicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my_playlists': {
      id: '/my_playlists'
      path: '/my_playlists'
      fullPath: '/my_playlists'
      preLoaderRoute: typeof My_playlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-songs': {
      id: '/my-songs'
      path: '/my-songs'
      fullPath: '/my-songs'
      preLoaderRoute: typeof MySongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-apps': {
      id: '/my-apps'
      path: '/my-apps'
      fullPath: '/my-apps'
      preLoaderRoute: typeof MyAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-albums': {
      id: '/my-albums'
      path: '/my-albums'
      fullPath: '/my-albums'
      preLoaderRoute: typeof MyAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interest': {
      id: '/interest'
      path: '/interest'
      fullPath: '/interest'
      preLoaderRoute: typeof InterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-pro': {
      id: '/go-pro'
      path: '/go-pro'
      fullPath: '/go-pro'
      preLoaderRoute: typeof GoProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fame': {
      id: '/fame'
      path: '/fame'
      fullPath: '/fame'
      preLoaderRoute: typeof FameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become': {
      id: '/become'
      path: '/become'
      fullPath: '/become'
      preLoaderRoute: typeof BecomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tracks/$slug': {
      id: '/tracks/$slug'
      path: '/tracks/$slug'
      fullPath: '/tracks/$slug'
      preLoaderRoute: typeof TracksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$slug': {
      id: '/playlists/$slug'
      path: '/$slug'
      fullPath: '/playlists/$slug'
      preLoaderRoute: typeof PlaylistsSlugRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/payment/cinetpay-callback': {
      id: '/payment/cinetpay-callback'
      path: '/payment/cinetpay-callback'
      fullPath: '/payment/cinetpay-callback'
      preLoaderRoute: typeof PaymentCinetpayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/withdraw': {
      id: '/artist/withdraw'
      path: '/artist/withdraw'
      fullPath: '/artist/withdraw'
      preLoaderRoute: typeof ArtistWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/upgrade': {
      id: '/artist/upgrade'
      path: '/artist/upgrade'
      fullPath: '/artist/upgrade'
      preLoaderRoute: typeof ArtistUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$slug': {
      id: '/albums/$slug'
      path: '/$slug'
      fullPath: '/albums/$slug'
      preLoaderRoute: typeof AlbumsSlugRouteImport
      parentRoute: typeof AlbumsRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracks': {
      id: '/admin/tracks'
      path: '/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof AdminTracksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/topups': {
      id: '/admin/topups'
      path: '/topups'
      fullPath: '/admin/topups'
      preLoaderRoute: typeof AdminTopupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/copyrights': {
      id: '/admin/copyrights'
      path: '/copyrights'
      fullPath: '/admin/copyrights'
      preLoaderRoute: typeof AdminCopyrightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cinetpay': {
      id: '/admin/cinetpay'
      path: '/cinetpay'
      fullPath: '/admin/cinetpay'
      preLoaderRoute: typeof AdminCinetpayRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branding': {
      id: '/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminBrandingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banned-ips': {
      id: '/admin/banned-ips'
      path: '/banned-ips'
      fullPath: '/admin/banned-ips'
      preLoaderRoute: typeof AdminBannedIpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bank-receipts': {
      id: '/admin/bank-receipts'
      path: '/bank-receipts'
      fullPath: '/admin/bank-receipts'
      preLoaderRoute: typeof AdminBankReceiptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artists': {
      id: '/admin/artists'
      path: '/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminArtistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artist-verification': {
      id: '/admin/artist-verification'
      path: '/artist-verification'
      fullPath: '/admin/artist-verification'
      preLoaderRoute: typeof AdminArtistVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/seed-test-accounts': {
      id: '/api/public/seed-test-accounts'
      path: '/api/public/seed-test-accounts'
      fullPath: '/api/public/seed-test-accounts'
      preLoaderRoute: typeof ApiPublicSeedTestAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flutterwave-webhook': {
      id: '/api/public/flutterwave-webhook'
      path: '/api/public/flutterwave-webhook'
      fullPath: '/api/public/flutterwave-webhook'
      preLoaderRoute: typeof ApiPublicFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cinetpay-webhook': {
      id: '/api/public/cinetpay-webhook'
      path: '/api/public/cinetpay-webhook'
      fullPath: '/api/public/cinetpay-webhook'
      preLoaderRoute: typeof ApiPublicCinetpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminArtistVerificationRoute: typeof AdminArtistVerificationRoute
  AdminArtistsRoute: typeof AdminArtistsRoute
  AdminBankReceiptsRoute: typeof AdminBankReceiptsRoute
  AdminBannedIpsRoute: typeof AdminBannedIpsRoute
  AdminBrandingRoute: typeof AdminBrandingRoute
  AdminCinetpayRoute: typeof AdminCinetpayRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminCopyrightsRoute: typeof AdminCopyrightsRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTopupsRoute: typeof AdminTopupsRoute
  AdminTracksRoute: typeof AdminTracksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminArtistVerificationRoute: AdminArtistVerificationRoute,
  AdminArtistsRoute: AdminArtistsRoute,
  AdminBankReceiptsRoute: AdminBankReceiptsRoute,
  AdminBannedIpsRoute: AdminBannedIpsRoute,
  AdminBrandingRoute: AdminBrandingRoute,
  AdminCinetpayRoute: AdminCinetpayRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminCopyrightsRoute: AdminCopyrightsRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTopupsRoute: AdminTopupsRoute,
  AdminTracksRoute: AdminTracksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AlbumsRouteChildren {
  AlbumsSlugRoute: typeof AlbumsSlugRoute
}

const AlbumsRouteChildren: AlbumsRouteChildren = {
  AlbumsSlugRoute: AlbumsSlugRoute,
}

const AlbumsRouteWithChildren =
  AlbumsRoute._addFileChildren(AlbumsRouteChildren)

interface PlaylistsRouteChildren {
  PlaylistsSlugRoute: typeof PlaylistsSlugRoute
}

const PlaylistsRouteChildren: PlaylistsRouteChildren = {
  PlaylistsSlugRoute: PlaylistsSlugRoute,
}

const PlaylistsRouteWithChildren = PlaylistsRoute._addFileChildren(
  PlaylistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlbumsRoute: AlbumsRouteWithChildren,
  BecomeRoute: BecomeRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  DiscoverRoute: DiscoverRoute,
  FameRoute: FameRoute,
  FaqRoute: FaqRoute,
  FavouritesRoute: FavouritesRoute,
  FeedRoute: FeedRoute,
  FollowingRoute: FollowingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GenresRoute: GenresRoute,
  GoProRoute: GoProRoute,
  ImportRoute: ImportRoute,
  InterestRoute: InterestRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MyAlbumsRoute: MyAlbumsRoute,
  MyAppsRoute: MyAppsRoute,
  MySongsRoute: MySongsRoute,
  My_playlistsRoute: My_playlistsRoute,
  New_musicRoute: New_musicRoute,
  NotificationsRoute: NotificationsRoute,
  PlaylistsRoute: PlaylistsRouteWithChildren,
  PointSystemRoute: PointSystemRoute,
  ProfileRoute: ProfileRoute,
  PurchasedRoute: PurchasedRoute,
  Recently_playedRoute: Recently_playedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SpotlightRoute: SpotlightRoute,
  SubscriptionRoute: SubscriptionRoute,
  Top_musicRoute: Top_musicRoute,
  UploadAlbumRoute: UploadAlbumRoute,
  UploadSingleRoute: UploadSingleRoute,
  UploadSongRoute: UploadSongRoute,
  WalletRoute: WalletRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArtistUpgradeRoute: ArtistUpgradeRoute,
  ArtistWithdrawRoute: ArtistWithdrawRoute,
  ArtistsSlugRoute: ArtistsSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  PaymentCinetpayCallbackRoute: PaymentCinetpayCallbackRoute,
  TracksSlugRoute: TracksSlugRoute,
  ApiPublicCinetpayWebhookRoute: ApiPublicCinetpayWebhookRoute,
  ApiPublicFlutterwaveWebhookRoute: ApiPublicFlutterwaveWebhookRoute,
  ApiPublicSeedTestAccountsRoute: ApiPublicSeedTestAccountsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
